#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
startup &

bspc config border_width 4
bspc config window_gap   8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a LearnOpenGL state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# autoloading programs
python3 -m pywal -R
urxvtd -q -o -f
polybar white &
xsetroot -cursor_name left_ptr
setxkbmap de,us -option grp:win_space_toggle
