---
- name: Check if nerd fonts already exists
  stat:
    path: "{{lookup('env', 'HOME')}}/.local/share/fonts/NerdFonts"
  register: nerdfonts

- name: Git clone nerdfonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerdfonts
  when: (not nerdfonts.stat.exists) and (install_nerdfonts | bool)

- name: Install nerdfonts
  command: "{{ item }} chdir=/tmp/nerdfonts"
  with_items:
    - ./install.sh
  when: (not nerdfonts.stat.exists) and (install_nerdfonts | bool)

- name: Remove git source for nerdfonts
  file:
    path: /tmp/nerdfonts
    state: absent
  when: (not nerdfonts.stat.exists) and (install_nerdfonts | bool)

