---
- name: Check if nerd fonts already exists
  stat:
    path: "{{lookup('env', 'HOME')}}/.fonts/JetBrains Mono Bold Nerd Font Complete.ttf"
  register: nerdfonts

- name: Check if the directory exists
  stat:
    path: "{{lookup('env', 'HOME')}}/.fonts/"
  register: nerdfonts_dir

- name: Make a dir if not exists
  file:
    path: "{{lookup('env', 'HOME')}}/.fonts/"
    state: directory

- name: Download and copy jetbrains fonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
    dest: "{{lookup('env', 'HOME')}}/.fonts"
    remote_src: yes
  when: (not nerdfonts.stat.exists)

- name: Update font cache
  command: "{{ item }} "
  with_items:
    -  fc-cache -f -v
